on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'CONTRIBUTING.md'
      - 'COPYING'
      - 'website/**'
      - '.github/*.md'
      - '.github/FUNDING.yml'

name: Build Code
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
    - name: Checkout code ðŸ‘‹
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
    - name: Install Go ðŸ—³
      uses: ./.github/workflows/composite/bootstrap-go
    - name: Run GoReleaser ðŸš€
      uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a
      with:
        distribution: goreleaser
        version: latest
        args: build --clean --snapshot --skip=post-hooks --skip=before
        workdir: src
    - name: Archive production artifacts
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
      with:
        name: builds
        retention-days: 1
        path: |
          src/dist
